name: Vault Terraform Demo
on: [push]

permissions:
  id-token: write  # Crucial for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch AWS Credentials from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://44.202.202.161:8200
          role: gh-actions-role
          method: jwt
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - uses: hashicorp/setup-terraform@v3
      - run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
